import resend
import os
from dotenv import load_dotenv

load_dotenv()

resend.api_key = os.getenv("RESEND_API_KEY")
FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL", "billing@snapface.app")


def send_invoice_email(
    to_email: str,
    client_name: str,
    invoice_number: str,
    total_amount: float,
    payment_url: str | None,
    photographer_name: str,
    pdf_bytes: bytes,
):
    try:
        params = {
            "from": f"SnapFace Billing <{FROM_EMAIL}>",
            "to": [to_email],
            "subject": f"Invoice {invoice_number} from {photographer_name}",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: #2563EB; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
                    <h1 style="color: white; margin: 0; font-size: 24px;">SnapFace</h1>
                    <p style="color: #BFDBFE; margin: 4px 0 0;">Photography Billing</p>
                </div>
                <div style="background: #F8FAFC; padding: 32px; border-radius: 0 0 12px 12px; border: 1px solid #E2E8F0;">
                    <p style="color: #0F172A; font-size: 16px;">Dear <b>{client_name}</b>,</p>
                    <p style="color: #64748B;">Please find your invoice attached from <b>{photographer_name}</b>.</p>

                    <div style="background: white; border: 1px solid #E2E8F0; border-radius: 8px; padding: 20px; margin: 20px 0;">
                        <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
                            <span style="color: #64748B;">Invoice Number</span>
                            <b style="color: #0F172A;">{invoice_number}</b>
                        </div>
                        <div style="display: flex; justify-content: space-between;">
                            <span style="color: #64748B;">Amount Due</span>
                            <b style="color: #2563EB; font-size: 20px;">₹{total_amount:,.2f}</b>
                        </div>
                    </div>

                    {"<a href='" + payment_url + "' style='display: block; background: #2563EB; color: white; text-align: center; padding: 14px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px;'>Pay Now →</a>" if payment_url else ""}

                    <p style="color: #94A3B8; font-size: 12px; margin-top: 24px; text-align: center;">
                        Invoice PDF is attached to this email.<br/>
                        Generated by SnapFace · AI Photo Sharing Platform
                    </p>
                </div>
            </div>
            """,
            "attachments": [
                {
                    "filename": f"Invoice_{invoice_number}.pdf",
                    "content": list(pdf_bytes),
                }
            ],
        }
        resend.Emails.send(params)
        return True
    except Exception as e:
        print(f"Email send error: {e}")
        return False


def send_payment_confirmation_email(
    to_email: str,
    client_name: str,
    invoice_number: str,
    total_amount: float,
    photographer_name: str,
):
    try:
        params = {
            "from": f"SnapFace Billing <{FROM_EMAIL}>",
            "to": [to_email],
            "subject": f"Payment Received — Invoice {invoice_number}",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: #16A34A; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
                    <div style="font-size: 48px;">✅</div>
                    <h1 style="color: white; margin: 8px 0 0;">Payment Received!</h1>
                </div>
                <div style="background: #F8FAFC; padding: 32px; border-radius: 0 0 12px 12px; border: 1px solid #E2E8F0;">
                    <p style="color: #0F172A;">Dear <b>{client_name}</b>,</p>
                    <p style="color: #64748B;">Your payment of <b style="color: #16A34A;">₹{total_amount:,.2f}</b> for invoice <b>{invoice_number}</b> has been successfully received by <b>{photographer_name}</b>.</p>
                    <div style="background: #DCFCE7; border: 1px solid #BBF7D0; border-radius: 8px; padding: 16px; text-align: center; margin: 20px 0;">
                        <p style="color: #166534; font-weight: bold; margin: 0;">Payment Confirmed ✓</p>
                        <p style="color: #166534; margin: 4px 0 0;">Amount: ₹{total_amount:,.2f}</p>
                    </div>
                    <p style="color: #94A3B8; font-size: 12px; text-align: center;">Thank you for your payment!</p>
                </div>
            </div>
            """,
        }
        resend.Emails.send(params)
        return True
    except Exception as e:
        print(f"Payment confirmation email error: {e}")
        return False