import resend
import os
from dotenv import load_dotenv

load_dotenv()

resend.api_key = os.getenv("RESEND_API_KEY")
FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL", "billing@snapface.app")


def send_invoice_email(
    to_email: str,
    client_name: str,
    invoice_number: str,
    total_amount: float,
    payment_url: str | None,
    photographer_name: str,
    pdf_bytes: bytes,
):
    try:
        params = {
            "from": f"SnapFace Billing <{FROM_EMAIL}>",
            "to": [to_email],
            "subject": f"Invoice {invoice_number} from {photographer_name}",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: #2563EB; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
                    <h1 style="color: white; margin: 0; font-size: 24px;">SnapFace</h1>
                    <p style="color: #BFDBFE; margin: 4px 0 0;">Photography Billing</p>
                </div>
                <div style="background: #F8FAFC; padding: 32px; border-radius: 0 0 12px 12px; border: 1px solid #E2E8F0;">
                    <p style="color: #0F172A; font-size: 16px;">Dear <b>{client_name}</b>,</p>
                    <p style="color: #64748B;">Please find your invoice attached from <b>{photographer_name}</b>.</p>

                    <div style="background: white; border: 1px solid #E2E8F0; border-radius: 8px; padding: 20px; margin: 20px 0;">
                        <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
                            <span style="color: #64748B;">Invoice Number</span>
                            <b style="color: #0F172A;">{invoice_number}</b>
                        </div>
                        <div style="display: flex; justify-content: space-between;">
                            <span style="color: #64748B;">Amount Due</span>
                            <b style="color: #2563EB; font-size: 20px;">₹{total_amount:,.2f}</b>
                        </div>
                    </div>

                    {"<a href='" + payment_url + "' style='display: block; background: #2563EB; color: white; text-align: center; padding: 14px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px;'>Pay Now →</a>" if payment_url else ""}

                    <p style="color: #94A3B8; font-size: 12px; margin-top: 24px; text-align: center;">
                        Invoice PDF is attached to this email.<br/>
                        Generated by SnapFace · AI Photo Sharing Platform
                    </p>
                </div>
            </div>
            """,
            "attachments": [
                {
                    "filename": f"Invoice_{invoice_number}.pdf",
                    "content": list(pdf_bytes),
                }
            ],
        }
        resend.Emails.send(params)
        return True
    except Exception as e:
        print(f"Email send error: {e}")
        return False


def send_payment_confirmation_email(
    to_email: str,
    client_name: str,
    invoice_number: str,
    total_amount: float,
    photographer_name: str,
):
    try:
        params = {
            "from": f"SnapFace Billing <{FROM_EMAIL}>",
            "to": [to_email],
            "subject": f"Payment Received — Invoice {invoice_number}",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: #16A34A; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
                    <div style="font-size: 48px;">✅</div>
                    <h1 style="color: white; margin: 8px 0 0;">Payment Received!</h1>
                </div>
                <div style="background: #F8FAFC; padding: 32px; border-radius: 0 0 12px 12px; border: 1px solid #E2E8F0;">
                    <p style="color: #0F172A;">Dear <b>{client_name}</b>,</p>
                    <p style="color: #64748B;">Your payment of <b style="color: #16A34A;">₹{total_amount:,.2f}</b> for invoice <b>{invoice_number}</b> has been successfully received by <b>{photographer_name}</b>.</p>
                    <div style="background: #DCFCE7; border: 1px solid #BBF7D0; border-radius: 8px; padding: 16px; text-align: center; margin: 20px 0;">
                        <p style="color: #166534; font-weight: bold; margin: 0;">Payment Confirmed ✓</p>
                        <p style="color: #166534; margin: 4px 0 0;">Amount: ₹{total_amount:,.2f}</p>
                    </div>
                    <p style="color: #94A3B8; font-size: 12px; text-align: center;">Thank you for your payment!</p>
                </div>
            </div>
            """,
        }
        resend.Emails.send(params)
        return True
    except Exception as e:
        print(f"Payment confirmation email error: {e}")
        return False
    
def send_storage_limit_email(
    to_email: str,
    name: str,
    used_label: str,
    limit_label: str,
    plan_name: str,
    upgrade_url: str,
):
    try:
        params = {
            "from": f"SnapFace <{FROM_EMAIL}>",
            "to": [to_email],
            "subject": "Storage limit reached — Upgrade your SnapFace plan",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: #DC2626; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
                    <div style="font-size: 48px;">⚠️</div>
                    <h1 style="color: white; margin: 8px 0 0;">Storage limit reached!</h1>
                </div>
                <div style="background: #F8FAFC; padding: 32px; border-radius: 0 0 12px 12px; border: 1px solid #E2E8F0;">
                    <p style="color: #0F172A;">Hi <b>{name}</b>,</p>
                    <p style="color: #64748B;">Your SnapFace account has reached its storage limit.</p>

                    <div style="background: #FEF2F2; border: 1px solid #FECACA; border-radius: 8px; padding: 16px; margin: 20px 0;">
                        <p style="color: #DC2626; font-weight: bold; margin: 0;">
                            {used_label} used of {limit_label} ({plan_name} plan)
                        </p>
                    </div>

                    <p style="color: #64748B;">
                        New photo uploads are blocked until you upgrade your plan or delete some photos.
                    </p>

                    <a href="{upgrade_url}" style="display: block; background: #2563EB; color: white; text-align: center; padding: 14px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px; margin-top: 20px;">
                        Upgrade Plan →
                    </a>

                    <p style="color: #94A3B8; font-size: 12px; margin-top: 24px; text-align: center;">
                        SnapFace · AI Photo Sharing Platform
                    </p>
                </div>
            </div>
            """,
        }
        resend.Emails.send(params)
        return True
    except Exception as e:
        print(f"Storage limit email error: {e}")
        return False


def send_subscription_expiry_warning(
    to_email: str,
    name: str,
    plan_name: str,
    days_remaining: int,
    renew_url: str,
):
    try:
        params = {
            "from": f"SnapFace <{FROM_EMAIL}>",
            "to": [to_email],
            "subject": f"Your SnapFace {plan_name} plan expires in {days_remaining} days",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: #D97706; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
                    <div style="font-size: 48px;">⏰</div>
                    <h1 style="color: white; margin: 8px 0 0;">Plan expiring soon!</h1>
                </div>
                <div style="background: #F8FAFC; padding: 32px; border-radius: 0 0 12px 12px; border: 1px solid #E2E8F0;">
                    <p style="color: #0F172A;">Hi <b>{name}</b>,</p>
                    <p style="color: #64748B;">Your <b>{plan_name}</b> plan expires in <b>{days_remaining} days</b>.</p>
                    <p style="color: #64748B;">After expiry, your account will be downgraded to the Free plan (2GB limit).</p>
                    <a href="{renew_url}" style="display: block; background: #2563EB; color: white; text-align: center; padding: 14px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px; margin-top: 20px;">
                        Renew Now →
                    </a>
                </div>
            </div>
            """,
        }
        resend.Emails.send(params)
        return True
    except Exception as e:
        print(f"Expiry warning email error: {e}")
        return False
    
def send_photos_ready_email(
    to_email: str,
    guest_name: str,
    event_name: str,
    photographer_name: str,
    guest_url: str,
):
    try:
        params = {
            "from": f"SnapFace <{FROM_EMAIL}>",
            "to": [to_email],
            "subject": f"📸 Your photos from {event_name} are ready!",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: #2563EB; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
                    <div style="font-size: 48px;">📸</div>
                    <h1 style="color: white; margin: 8px 0 0;">Your photos are ready!</h1>
                </div>
                <div style="background: #F8FAFC; padding: 32px; border-radius: 0 0 12px 12px; border: 1px solid #E2E8F0;">
                    <p style="color: #0F172A;">Hi <b>{guest_name}</b>,</p>
                    <p style="color: #64748B;">
                        Great news! Your photos from <b>{event_name}</b> by <b>{photographer_name}</b> are now ready to view and download.
                    </p>
                    <p style="color: #64748B;">
                        Upload a selfie to instantly find all your photos using our AI face recognition.
                    </p>
                    <a href="{guest_url}" style="display: block; background: #2563EB; color: white; text-align: center; padding: 14px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px; margin-top: 20px;">
                        Find my photos →
                    </a>
                    <p style="color: #94A3B8; font-size: 12px; margin-top: 24px; text-align: center;">
                        Powered by SnapFace · AI Photo Sharing
                    </p>
                </div>
            </div>
            """,
        }
        resend.Emails.send(params)
        return True
    except Exception as e:
        print(f"Photos ready email error: {e}")
        return False